# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d749f9de1fd79f9b55acea145c36a0d904907a049b36e433b872bf847b09eb0f4a169c389564d9d996361c05acc8ed10951de60162509704ace5fbb577bf7b71

test:
  secret_key_base: b6703fc4038048a4dd44e5de9793cdaabcc28dfb8629af2ea3cce0651538719b3c73a95474f83f3f965ef480721ed93b6024c76d5c85ded681a05e6cbd57392d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
